# Tangly installer — Windows (PowerShell).
#
# Usage:
#   iwr -useb https://tangly.dev/install.ps1 | iex
#   $env:TANGLY_VERSION = '0.0.5'; iwr -useb https://tangly.dev/install.ps1 | iex
#
# Env vars:
#   TANGLY_VERSION  — pin to specific version. Default: latest.
#   TANGLY_BIN_DIR  — install dir for the `tangly` wrapper. Default: $env:LOCALAPPDATA\tangly\bin.
#   TANGLY_PM       — runner: "bun" | "npm". Default: bun if available, else npm.
#
# What this does
# --------------
# Tangly drives Astro at build time; Astro's plugin universe needs real
# on-disk node_modules. A globally-installed tangly fails to resolve
# transitive deps from inside your project dir. This installer writes a
# thin wrapper that delegates to `bunx --bun tangly@<version>` (or
# `npx tangly@<version>`) on every invocation. First run per version
# downloads ~80MB; subsequent runs hit the cache.

$ErrorActionPreference = "Stop"

function Write-Log  { param($Message) Write-Host "==> "      -ForegroundColor Green  -NoNewline; Write-Host $Message }
function Write-Info { param($Message) Write-Host ":: "       -ForegroundColor Blue   -NoNewline; Write-Host $Message }
function Write-Warn { param($Message) Write-Host "Warning: " -ForegroundColor Yellow -NoNewline; Write-Host $Message }
function Write-Err  { param($Message) Write-Host "Error: "   -ForegroundColor Red    -NoNewline; Write-Host $Message; exit 1 }

$Version    = if ($env:TANGLY_VERSION) { $env:TANGLY_VERSION } else { "latest" }
$BinDir     = if ($env:TANGLY_BIN_DIR) { $env:TANGLY_BIN_DIR } else { Join-Path $env:LOCALAPPDATA "tangly\bin" }
$PmOverride = if ($env:TANGLY_PM)      { $env:TANGLY_PM }      else { "auto" }

Write-Host ""
Write-Host "  _____                _      "
Write-Host " |_   _|_ _ _ __   __ _| |_   _ "
Write-Host "   | |/ _`` | '_ \ / _`` | | | | |"
Write-Host "   | | (_| | | | | (_| | | |_| |"
Write-Host "   |_|\__,_|_| |_|\__, |_|\__, |"
Write-Host "                  |___/   |___/"
Write-Host ""

function Pick-Pm {
    if ($PmOverride -eq "bun") {
        if (-not (Get-Command bun -ErrorAction SilentlyContinue)) {
            Write-Err "TANGLY_PM=bun but 'bun' is not on PATH"
        }
        return "bun"
    }
    if ($PmOverride -eq "npm") {
        if (-not (Get-Command npx -ErrorAction SilentlyContinue)) {
            Write-Err "TANGLY_PM=npm but 'npx' is not on PATH"
        }
        return "npm"
    }
    if (Get-Command bun -ErrorAction SilentlyContinue) { return "bun" }
    if (Get-Command npx -ErrorAction SilentlyContinue) { return "npm" }

    Write-Err @"
Neither bun nor npx found. Install one first:
  bun:  powershell -c "irm bun.sh/install.ps1 | iex"
  node: https://nodejs.org/ (includes npm/npx)
"@
}

$Pm = Pick-Pm
Write-Log "Runner: $Pm"

if ($Version -eq "latest") {
    Write-Log "Resolving latest tangly version from npm…"
    try {
        $resolved = (Invoke-RestMethod -Uri "https://registry.npmjs.org/tangly/latest" -TimeoutSec 30).version
    } catch {
        Write-Err "Failed to fetch tangly version from npm registry: $_"
    }
    if (-not $resolved) {
        Write-Err "Could not parse latest version from npm registry response"
    }
    Write-Log "Latest: $resolved"
    $Version = $resolved
} else {
    $Version = $Version.TrimStart('v')
    Write-Log "Pinning to: $Version"
}

# Prepare bin dir.
if (-not (Test-Path $BinDir)) {
    New-Item -ItemType Directory -Path $BinDir -Force | Out-Null
}

# Write wrapper as a .cmd file (Windows shell wrapper).
$wrapperPath = Join-Path $BinDir "tangly.cmd"
$wrapperContent = @"
@echo off
REM Auto-generated by Tangly installer. Pinned to tangly@$Version.
REM To upgrade: re-run the installer.
set TANGLY_VERSION=$Version
"@

switch ($Pm) {
    "bun" {
        $wrapperContent += "`r`nbunx --bun tangly@%TANGLY_VERSION% %*`r`n"
    }
    "npm" {
        $wrapperContent += "`r`nnpx --yes tangly@%TANGLY_VERSION% %*`r`n"
    }
}

Set-Content -Path $wrapperPath -Value $wrapperContent -Encoding ASCII
Write-Log "Wrote $wrapperPath (pinned tangly@$Version via $Pm)"

# Warm the cache.
Write-Log "Warming cache…"
try {
    & $wrapperPath --version | Out-Null
    Write-Info "Cache warmed."
} catch {
    Write-Warn "Cache warm-up failed; first invocation will download deps."
}

# PATH check
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
$onPath = ($env:Path -split ';') -contains $BinDir -or ($userPath -split ';') -contains $BinDir

if (-not $onPath) {
    Write-Warn "$BinDir is not on PATH."
    Write-Info "Add to user PATH (permanent):"
    Write-Info "  [Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path', 'User') + ';$BinDir', 'User')"
    Write-Info "Or for this session only:"
    Write-Info "  `$env:Path += ';$BinDir'"
}

Write-Host ""
Write-Host "Installed: tangly@$Version (wrapper at $wrapperPath)" -ForegroundColor Green
Write-Host ""
Write-Host "Get started:"
Write-Host "  mkdir my-docs; cd my-docs"
Write-Host "  tangly init             # interactive scaffold"
Write-Host "  tangly dev              # dev server"
Write-Host "  tangly build            # static build -> dist/"
Write-Host ""
Write-Host "To upgrade later:"
Write-Host "  iwr -useb https://tangly.dev/install.ps1 | iex"
Write-Host ""
Write-Host "Docs:    https://tangly.dev"
Write-Host "Issues:  https://github.com/tanglydocs/tangly/issues"
Write-Host ""
