name = "tangly"
auto_start = true

[tasks.docs]
command = "../packages/tangly/bin/tangly.js dev --no-open --port $PORT"
cwd = "docs"
host = "docs"
auto_start = false
restart_policy = "on-failure"

[tasks.tang]
command = "../../packages/tangly/bin/tangly.js dev --no-open --port $PORT"
cwd = "examples/demo-tang"
host = "tang"
auto_start = false
restart_policy = "on-failure"

[tasks.pith]
command = "../../packages/tangly/bin/tangly.js dev --no-open --port $PORT"
cwd = "examples/demo-pith"
host = "pith"
auto_start = false
restart_policy = "on-failure"

[tasks.pip]
command = "../../packages/tangly/bin/tangly.js dev --no-open --port $PORT"
cwd = "examples/demo-pip"
host = "pip"
auto_start = false
restart_policy = "on-failure"

[tasks.readable]
command = "../../packages/tangly/bin/tangly.js dev --no-open --port $PORT"
cwd = "examples/demo-readable"
host = "readable"
auto_start = false
restart_policy = "on-failure"

[tasks.geist]
command = "../../packages/tangly/bin/tangly.js dev --no-open --port $PORT"
cwd = "examples/demo-geist"
host = "geist"
auto_start = false
restart_policy = "on-failure"

[tasks.starter]
command = "../../packages/tangly/bin/tangly.js dev --no-open --port $PORT"
cwd = "examples/demo-starter"
host = "starter"
auto_start = false
restart_policy = "on-failure"
